# @package dataset
defaults:
  - /dataset/default
_target_: lightning_transformers.core.nlp.HFDataModule
cfg:
  dataset_name: null
  dataset_config_name: null # only used to name the cache directory?
  pretrained_dataset_name: ${dataset.cfg.dataset_name}
  train_file: null
  validation_file: null
  test_file: null
  train_val_split: null
  max_samples: null
  cache_dir: null
  padding: 'max_length'
  truncation: 'only_first'
  preprocessing_num_workers: 1
  load_from_cache_file: True
  max_length: 128
  limit_train_samples: null
  limit_val_samples: null
  limit_test_samples: null
