# @package task
defaults:
  - nlp/default
  - override /backbone@_group_: nlp/seq2seq # Swap to a default seq2seq compatible backbone
  - override /dataset@_group_: nlp/conversation/default
_target_: lightning_transformers.task.nlp.conversation.ConversationTransformer
downstream_model_type: transformers.AutoModelForSeq2SeqLM
cfg:
  use_stemmer: True
  rouge_newline_sep: True
  val_target_max_length: 128
  num_beams: null
  compute_generate_metrics: True

max_length: 128
