# @package task
defaults:
  - nlp/default
  - override /dataset@_group_: nlp/text_regression/default
_target_: lightning_transformers.task.nlp.text_regression.TextRegressionTransformer
downstream_model_type: transformers.BertModel
cfg:
  task_name: text_regression
