defaults: # loads default configs
  - dpp_multi_hist2

dataset:
  _target_: lightning_transformers.task.nlp.text_regression.HierarchicalTextRegressionMultiDataModule
  cfg:
    hierarchical: True

training:
  run_test_after_fit: False

task:
  _target_: lightning_transformers.task.nlp.text_regression.HierarchicalTextRegressionTransformer
  cfg:
    task_name: text_regression_hier_hist
    pooling_method: first