defaults: # loads default configs
  - dpp_multi_hist2
  - override scheduler: constant_schedule_with_warmup

dataset:
  _target_: lightning_transformers.task.nlp.text_regression.HierarchicalTextRegressionMultiDataModule
  cfg:
    hierarchical: True

training:
  lr: 5e-5
  run_test_after_fit: False

task:
  _target_: lightning_transformers.task.nlp.text_regression.HierarchicalTextRegressionTransformer
  cfg:
    task_name: text_regression_hier_hist
    pooling_method: mean

seed: 11
