_target_: pytorch_lightning.callbacks.ModelCheckpoint

dirpath: ${trainer.default_root_dir}
filename: '{epoch:02d}-{${task.cfg.scheduler_monitor}:.2f}'
monitor: ${task.cfg.scheduler_monitor}
mode: ${task.cfg.scheduler_mode}
save_last: True
save_top_k: 1