# @package dataset
defaults:
  - /dataset/nlp/default
_target_: lightning_transformers.task.nlp.conversation.ConversationDataModule
cfg:
  max_source_length: 128
  max_target_length: 128
  history_delimiter: '  '
  padding: False
