# @package dataset
defaults:
  - /dataset/nlp/conversation/default
_target_: lightning_transformers.task.nlp.conversation.ConversationDataModule
cfg:
  dataset_name: my_dstc8_reddit_dialogue
  preprocessing_num_workers: 30
