# @package dataset
defaults:
  - /dataset/nlp/conversation/default
_target_: lightning_transformers.task.nlp.conversation.ConversationDataModule
cfg:
  dataset_name: my_wizard_of_wikipedia
  # dataset_config_name: 1.0.0
